// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image4":
            case "myImage1 all l":return img`
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
.................................................fff................................................
.........................................fffffffffffff..............................................
......................................fffbbbffffffffcfff............................................
.....................................fbbbbcccfffffccccccf...........................................
....................................bbbccccccccfcccccccccff.........................................
....................................bbccccccccccccccccccccc.........................................
...................................fbbbbccccccfccccccccccccf........................................
...................................fdbbdcccbbbfccbbbcccccccf........................................
..................................fbddbbfbbbbbfcbbbbbccbbccff.......................................
.................................ffbbbbfbddbbcfcbdbbbccbbbcbf.......................................
.................................fbbbbbfbbdbbffcbddbdccbddcdf.......................................
................................fbbcbccfbbbbfffcddbbdcfbbdfbff......................................
..............................ffbbffcccffbccfbfbcdbbbcfcbbcccf......................................
...................................fcccffccfbbfbccccccfccccccf......................................
..............................ffffffcccffcffdbfbccccccfccccccf......................................
..............................fffffbccfffffbddbfbcffccfccccfcfff....................................
.............................fbffffbccffffbbddbfbcffccfccccfcffff...................................
.............................fbffffbccffffffdddfbcffcccfcccfffffff..................................
.............................fbffffbcfffffffdddbfbffbccfcccfffffcf..................................
.............................fbcfffbccffcccfddddbfffbbcfcccfffffcf..................................
.............................fbcfffbbcffbdbfdd1ddffbfbcfcccfffffcf..................................
.............................fbcfffbbcffffffd11dddfffbbcfccffffccf..................................
.............................fbcfffbfbffbbbdddcddddbbfbcfccffffccf..................................
.............................fbcfffcfbcfbbbddddddddbbffbbfcfffcccf..................................
.............................fbccffffbcfbbbddddddddbbfffffffffcccf..................................
.............................fbccffffffcffdddddddddddfbcfccffbccf...................................
.......................fffff.fccff..fffbfffdddddddddffbffccffbccf...................................
.....................ffffffffcccf....ffbf.ffffffffff.ff..fcffbccf...................................
.....................fccff...ffff....ffff....fffff...f...fc.fbccf...................................
.....................ccf..............fff....fffbf.......fc..fbcf...................................
.....................ccf...............ff....ffbbf..fff..ff..ffbcf..................................
.....................ff................fffffffbbbffffcff..f....fffffffff............................
.....................ff................fffcfbbbbbbbbfccff.f........fffff............................
.....................fff...............fbccfdbbbbbbdfccbfff.........ffccf...........................
......................ff...............fbcccddddddddcccfbf...........fcff...........................
......................................fbbbccffddddddccfbbbf..........fcff...........................
......................................fccffffffffffffffcccf..........fff............................
......................................fccfcffffffffffcfcccc.........ff..............................
.....................................fbbbfbbbbbbbbbbbbfbbbb.........................................
.....................................fbbbfbbbbbbbbbbbbfbbbbf........................................
....................................fbbbbfbbbbbbbbbbbbffbbbf........................................
....................................fccbbfbbbbbbbbbbbbbfbbbf........................................
....................................fccccfcccccccccccccfcccc........................................
....................................fccccfcccccccccccccfccccf.......................................
....................................bbccffcccccccccccccfcccbf.......................................
....................................bbbbcfcccccccccccccffcbbf.......................................
....................................bbbbcfbbbbbbbbbbbbbbfcbbf.......................................
....................................cbbbcfbbbbbbbbbbbbbbfcbbf.......................................
....................................cccbcfbbbbbbbbbbbbbbfcbbcf......................................
....................................ccccffbbbbbbbbbbbbbbfcbccf......................................
...................................fbbbcffccccccccccccccffccbf......................................
...................................fbbbbffccccccccccccccffcbbbf.....................................
...................................fbbbbffccccccccccccccffbbbbf.....................................
..................................fffbbbffbbbbbbbbbbbbbbffbbbfff....................................
...................................fbfbbffbbbbbbbbbbbbbbfffffbbf....................................
..................................ffbbfffffffffffffffffffffbbbbdf...................................
..................................fdbbbbffffffffffffffffffbbbdddf...................................
..................................fdddbbffffffffffffffffffbbbdddf...................................
...................................fdddbfffffffffffffffffffddddff...................................
...................................fffdfffffffffffffffffff.ffdff....................................
.....................................fffffffffffffffffffff..ff......................................
........................................ffffffffffffffffff..........................................
........................................cfffffffffffffffff..........................................
........................................cfffffffffffffffff..........................................
........................................cfffffcfffffffffff..........................................
........................................cffffffccfffffffff..........................................
........................................cfffffff...cffffff..........................................
........................................cfffffff...cffffff..........................................
........................................cfffffff...cffffff..........................................
........................................ccffffff...cffffff..........................................
........................................ccffffff...cffffff..........................................
........................................ccffffff...cffffff..........................................
........................................ccffffff...cffffff..........................................
........................................ccffffff...cffffff..........................................
........................................ccffffff...cffffff..........................................
........................................ccffffff...cffffff..........................................
........................................ccffffff...cffffff..........................................
........................................ccffffff...cffffff..........................................
........................................ccffffff...cfffffff.........................................
........................................ccffffff...cfffffff.........................................
........................................ccffffff...cfffffff.........................................
........................................ccffffff...cfffffff.........................................
........................................ccffffff...cffffffff........................................
.......................................cccffffff...cfffffffff.......................................
.......................................ccffffffff..cfffffffff.......................................
.......................................cfffffffff..cfffffffff.......................................
.......................................cfffffffff..cfffffff.........................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
`;
            case "image1":
            case "Merlin":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . c c c c . . . . . . 
. . . . . c c c b b c . . . . . 
. . . . c c d c c b c c . . . . 
. . . . c c c d c c c c . . . . 
. . . c . c b d d b c . c . . . 
. . . . . . c d d c . . . . . . 
. . . . . b b b b b b . . . . . 
. . . . . c c c c c c . . . . . 
. . . . . b b b b b b . . . . . 
. . . . . d c c c c d . . . . . 
. . . . . . b b b b . . . . . . 
. . . . . . f . . f . . . . . . 
. . . . . . f . . f . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "myImage2":return img`
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
`;
            case "#Ut#s/2)Z+[(6HBZ!#NA":
            case "cloud place":return img`
ffffffffffffffffffff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff1fffffffffffffff1fffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffddddddddffffffffffffffffffffffffff111f
fffffffffffffffffffffffffffffffff1ffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffdddddddddddddffffffffffffffffff1ffffff1ff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddfffffffffffff1111ffffffffffddddddddddddddddddffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddfffffffff1ffffffffffddddddddddddddddddddddffffffffffffffffffffffff
ffffffdddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddddfffffff1fffffffffddddddddddddddddddddddddfffffffffffffffffffffff
ffffddddddddddddffffffffffffdddddddddddddffffffffffffffffffffdddddfffffffffdddddddddddddddddddddddfffffffffffffddddddddddbbbbbdddddddddddddddddddfffffffffffffff
ddddddddddddddddddfffffffffddddddddddddddddddddfffffffffffffdddddddfffffffddddddddddddddddddddddddddfffffffffddddddddbbbbbbbbbbbbbbddddddddddddddddffffffff1ffff
ddddddddddddddddddfffffffdddddddddddddddddddddddddddddfffffdddddddddfffffddddbbbbbbbbbbdddddddddddddddfffffdddddddbbbbbbbbbbbbbbbbbbbdddddddddddddddffffffffffff
dddddddddddddddddddffffffddddddddddddddddbbbbbbddddddddffffdddddddddddffdddbbbbbbbbbbbbbbbdddddddddddddfffddddddddbbbbbbbbbbbbbbbbbbbbbdddddddddddddffffffffffff
ddddddddddddddddddddfffddddddddddbbbbbbbbbbbbbbbbddddddfffdddbbbbddddddddbbbbbbbbbbbbbbbbbbbddddddddddddffdddddddbbbbbbbbbbbbbbbbbbbbbbbbddddddddddddfffffffffff
dddddddddddddddddddddfddddddddbbbbbbbbbbbbbbbbbbbbbbddddffddbbbbbbddddddbbbbbbbbbbbbbbbbbbbbbddddddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbddddddddddddffffffffff
dddddbbbbbddddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbdddfddbbbbbbbdddbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddffffffffff
dddbbbbbbbbbbbbbbbddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddbbbbbbbbbbbbbbdddddddddbdbbbbbbbbbddddbbbdddddfffffffdd
dbbbbbbbbbbbbbbbbbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddbbbbbbbbbbbbbbddddddddddddddbbbbbbbbbdbbbbbbbbddfffffdddd
bbbbbbbbbbbbbbbbbbbbbdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddbbbbbbbbbbbbbdddddddddddddddddddbbbbbbbbbbbbbbbbddfffddddd
bbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddbbbbbbbbbbbbbddddddddddddddddddddbbbbbbbbbbbbbbbbdddfdddddd
bbbbbbbbbbbbbbbbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbbbbddcccccccccddddddddddbbbbbbbbbbbbbbbbdddddddddd
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbbbddcccccccccccccdddddddbbbbbbbbbbbbbbbbddddddbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbbbbddccccccccccccccccddddddbbbbbbbbbbbbbbbddbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdcccccccccccccccccccdddddbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddcccccccccccccccccccccdddddddddddbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddddccccccccccccccccccccddddddddcccdddbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddccccccccccccccccccccccccddddcccccccccddbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbb
cccbbbbbbbbbddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddcccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbb
cccccbbbbbddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddcccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbb
ccccccbbbdddccdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddbdddccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbb
ccccccbcccccccddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddddccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbb
ccccccccccccccccddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbbdddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccdddcdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbcccc
cccccccccccccccccccccccccddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbb
ccccccccccccccccccccccccccdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccdddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbb
ccccccccccccccccccccccccccccddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddd
cccccccccccccccccccccccccccccccddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddddddddddddd
cccccccccccccccccccccccccccccccccddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddddddddddddd
ccccccccccccccccccccccccccccccccccccdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddcccccccccccdddddddccccccd
cccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddccccccccccccccdddddcccccccc
cccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddccccccccccccccccccccccccccc
bcccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddcccccccccccccccccccccccccccc
bccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddcccccccccccccccccccccccccccccc
bbbbbbbbbcccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddccccccccccccccccccccccccccccccc
bbbbbbbbbbccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddcccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbcccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddccccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbbbbbccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddbbbbbbdddddccccccccccccccccccccccccccccccccccc
cccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddddddddccccccccccccccccccccccccccccccccccc
cccccccddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddddddddddddddddddccccccccccccccccccccccccccccccccccc
cccccccccddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddddccccccccccddddddccccccccccccccccccccccccccccccccccc
ccccccccccddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddcccccccccccccccccccccccccccccccccccccccccccccccccccccbbbb
ccccccccccccccddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbb
cccccccccccccccddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbb
cccccccccccccccccdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddcccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbb
cccccccccccccccccccdddddddddbbbbbbbbbbbbbbbbbbbbbbdddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddcccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbb
ccccccccccccccccccccdddddddddddbbbbbbbbbbbbbbddddddddddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbb
cccccccccccccccccccdddddddddbbddbbbbbbbbbbbdddddddddddddddddddddddbbbbbbbbbdddddddbbbbbbbbbbbddddcccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbb
ccccccccccccccccccdddbbbbbbbbbbbbbbbbbbbbccccccccccddbbbbbbbbbbbbddbbbbbbdddddddddddbbbbbbbbbddddccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbb
ccccccccccccccccccdbbbbbbbbbbbbbbbbbbbcccccccccccccccccbbbbbbbbbbbbbbbdddddddddddddddbbbbbbbdddddcccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbb
cccccccccccccccccddbbbbccccccbbbbbbccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbdddddddddbbbbbbddddccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbb
ccccccccccccccccddbbbcccccccccccbbbbcccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbdddddddbbbbbdddccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbb
cccccccccccccccccbbbcccccccccccccbbbccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbddddddbbbbdddcccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbb
ccccccccccccccccccccccccccccccccccbbcccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbddddbbbbddccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbb
ccccccccccccccccccccccccccccccccccbbcccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbdddbbbdddcccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
ccccccccccccccccccccccccccccccccccbbcccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbddddbbddcccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccccccccbcccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbdddcccccccccddddddddddddddddddcccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbdddccccdddddddddddddddddddddddddccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbdddddddddbbbbbbbbbbdddddddddddddddcccbccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddccccccbbbbbbbbbbbbbbbbbbbbbbbbbbb
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddcccccbbbbbbbbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddcccbbbbbbbbbbbbbbbbbbbbbbbbb
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbccccccccccccccccbbbccbbbbbbbbbbbbbbbbbbddccccbbbbbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbcccccccccccccccccccccccccccbbbbbbbbbbbbbbbdddcccccbbbbbbbbbbbbbbbbbbbb
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbcccccccccccccccccccccccccccccccccbbbbbbbbbbbbbdddccccbbbbbbbbbbbbbbbbbbb
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbddcccccbbbbbbbbbbbbbbbbbb
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbcccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbddccccbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbdcccccbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbdcccccbbbbbbcccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbdcccccbbbbcccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbdccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbccccccccdddddddcccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbcccccddddddddddddcccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbccccddddddddddddddddc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbcccddddbbbbbbbbbddddd
ccccccccccccccccccccccccccccccccccccccccccdddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbdddbbbbbbbbbbbbbbbbdd
ccccccccccccccccccccccccccccccccccccccddddddddddddddddddddccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbb
cccccccccddddddccccccccccccccccccccdddddddddddddddddddddbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbb
cccccccdddddddddddccccccccccccccccdddddddddddbbbbdddddbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbccccbbbbbbb
ccccccddddddddddddddccccccccccccdddddddddddbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbcccccccccbbbb
ccccddddddddddddddddddcccccccccdddddddbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbccccccccccccccccccc
ccdddddddddddddddddddddcccccccddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
dddddddddbbbbbbbbbdddddddccccdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ddddddbbbbbbbbbbbbbbddddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ddddbbbbbbbbbbbbbbbbbbbdddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ddbbbbbbbbbbbbbbbbbbbbbddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
dbbbbbbbbbbbbbbbbbbbbbbbddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`;
            case "image8":
            case "Moon":return img`
. . . 5 5 5 5 5 5 . . . . . . . 
. . 5 5 5 5 5 . . . . . . . . . 
. 5 5 5 5 5 . . . . . . . . . . 
5 5 5 5 5 5 . . . . . . . . . . 
5 5 5 5 5 . . . . . . . . . . . 
5 5 5 5 5 . . . . . . . . . . . 
5 5 5 5 5 . . . . . . . . . . . 
5 5 5 5 5 . . . . . . . . . . . 
5 5 5 5 5 . . . . . . . . . . 5 
5 5 5 5 5 5 . . . . . . . . 5 5 
5 5 5 5 5 5 5 5 . . . . . 5 5 5 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 . 
. 5 5 5 5 5 5 5 5 5 5 5 5 5 5 . 
. . 5 5 5 5 5 5 5 5 5 5 5 . . . 
. . . 5 5 5 5 5 5 5 5 . . . . . 
`;
            case "image9":
            case "MoonGoddess":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 8 8 8 8 8 . . . . . . . 
. . . . 8 5 8 8 8 8 . . . . . . 
. . . 8 8 8 d d 1 8 . . . . . . 
. . 8 8 8 5 d d 5 . . . . . . . 
. 8 8 8 8 b d d b . . . . . . . 
. 8 8 8 c c c c c c . . . . . . 
8 8 8 . c c c c c c . . . . . . 
8 8 . . b b c c c c . . . . . . 
. 8 . . d b b b c c c . . . . . 
. . 8 . . d d b b b b . . . . . 
. . . . . . d d d d d . . . . . 
. . . . . . . 1 1 1 1 . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image5":
            case "CloudGirl":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 1 1 1 . . 1 1 1 . . . . 
. . . . 1 1 1 1 1 1 1 1 . . . . 
. . . . 1 1 1 1 1 1 1 1 . . . . 
. . . . . 1 9 d d 9 1 . . . . . 
. . . . 1 1 6 d d 6 1 1 . . . . 
. . . . . 9 9 9 9 9 9 . . . . . 
. . . . . 9 9 9 5 9 9 . . . . . 
. . . . . 9 9 9 1 9 9 . . . . . 
. . . . . 1 1 1 1 1 1 . . . . . 
. . . . . . 1 1 1 1 . . . . . . 
. . . . . . f . . f . . . . . . 
. . . . . . f . . f . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image7":
            case "CloudGuy":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . 1 1 1 1 . . . . . . 
. . . . . 1 1 1 1 1 1 . . . . . 
. . . . . 1 1 1 1 1 1 . . . . . 
. . . . . 1 9 d d 9 1 . . . . . 
. . . . . . 6 d d 6 . . . . . . 
. . . . . 9 9 9 9 9 9 . . . . . 
. . . . . 9 9 9 5 9 9 . . . . . 
. . . . . 9 9 9 1 9 9 . . . . . 
. . . . . 1 1 1 1 1 1 . . . . . 
. . . . . . 1 1 1 1 . . . . . . 
. . . . . . f . . f . . . . . . 
. . . . . . f . . f . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image3":
            case "stairsagainwow":return img`
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
......d11111111d......
......bddddddddb......
`;
            case "image2":
            case "BackupDoNotUse":return img`
. . . 5 5 5 5 5 5 . . . . . . . 
. . 5 5 5 5 5 . . . . . . . . . 
. 5 5 5 5 5 . . . . . . . . . . 
5 5 5 5 8 8 8 8 8 . . . . . . . 
5 5 5 5 8 5 8 8 8 8 . . . . . . 
5 5 5 8 8 8 d d 1 8 . . . . . . 
5 5 8 8 8 5 d d 5 . . . . . . . 
5 8 8 8 8 b d d b . . . . . . . 
5 8 8 8 c c c c c c . . . . . 5 
8 8 8 5 c c c c c c . . . . 5 5 
8 8 5 5 b b c c c c . . . 5 5 5 
5 8 5 5 d b b b c c c 5 5 5 5 5 
5 5 8 5 5 d d b b b b 5 5 5 5 . 
. 5 5 5 5 5 d d d d d 5 5 5 5 . 
. . 5 5 5 5 5 1 1 1 1 5 5 . . . 
. . . 5 5 5 5 5 5 5 5 . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "song1":
            case "Peaceful_Soundtrack1":return hex`005a0004080a0200001c00010a006400f4016400000400000000000000000000000000050000049c0038003c0001123c004000011440004c00011b4c005400012754005c0001275c006000012560006400012580008400012584008800012488009000012490009800012098009c0001259c00a8000124c000c800011ec800cc000127cc00d8000125e800f000011df000f4000124f4000001012204010801012008010c0101200c011001012010011401012014011c01011e1c012001012220013001011909010e02026400000403780000040a000301000000640001c80000040100000000640001640000040100000000fa0004af00000401c80000040a00019600000414000501006400140005010000002c0104dc00000401fa0000040a0001c8000004140005d0076400140005d0070000c800029001f40105c201f4010a0005900114001400039001000005c201f4010500058403050032000584030000fa00049001000005c201f4010500058403c80032000584030500640005840300009001049001000005c201f4010500058403c80064000584030500c8000584030000f40105ac0d000404a00f00000a0004ac0d2003010004a00f0000280004ac0d9001010004a00f0000280002d00700040408070f0064000408070000c80003c800c8000e7d00c80019000e64000f0032000e78000000fa00032c01c8000ee100c80019000ec8000f0032000edc000000fa0003f401c8000ea901c80019000e90010f0032000ea4010000fa0001c8000004014b000000c800012c01000401c8000000c8000190010004012c010000c80002c800000404c8000f0064000496000000c80002c2010004045e010f006400042c010000640002c409000404c4096400960004f6090000f40102b80b000404b80b64002c0104f40b0000f401022003000004200300040a000420030000ea01029001000004900100040a000490010000900102d007000410d0076400960010d0070000c800ea00000001000112080009000112100011000112180019000112200021000112280029000112300031000112380039000112400041000112480049000112500051000112580059000112600061000112680069000112700071000112780079000112800081000112880089000112900091000112980099000112a000a1000112a800a9000112b000b1000112b800b9000112c000c1000112c800c9000112d000d1000112d800d9000112e000e1000112e800e9000112f000f1000112f800f9000112000101010112080109010112100111010112180119010112200121010112280129010112300131010112`;
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
